wip: ci

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -51,69 +51,70 @@ jobs:
 
       - name: Install dependencies
         run: |
-          make deps
-          wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
-          sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb
-
-      - name: Install/Downgrade MongoDB to version 3.6
-        run: |
-          wget -qO - https://pgp.mongodb.com/server-3.6.asc | sudo tee /etc/apt/trusted.gpg.d/mongodb-org-3.6.gpg
-          echo "deb [trusted=yes arch=amd64] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/3.6 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.6.list
-          sudo apt-get update
-          sudo apt-get install -y --allow-downgrades mongodb-org=3.6.20 mongodb-org-server=3.6.20 mongodb-org-shell=3.6.20 mongodb-org-mongos=3.6.20 mongodb-org-tools=3.6.20 || echo "Error is misleading, it was successfully installed"     
-
-      #      - name: Install/Downgrade MongoDB to version 3.6
-      #        run: |
-      #          wget -qO - https://www.mongodb.org/static/pgp/server-3.6.asc | sudo apt-key add -
-      #          echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/3.6 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.6.list
-      #          sudo apt-get update
-      #          sudo apt-get install -y --allow-downgrades mongodb-org=3.6.20 mongodb-org-server=3.6.20 mongodb-org-shell=3.6.20 mongodb-org-mongos=3.6.20 mongodb-org-tools=3.6.20 || echo "Error is misleading, it was successfully installed"
-
-      - name: Unit Tests
-        run: glide novendor| xargs go test -v
-
-      #      - name: Create cover profile
-      #        run: make coverprofile
-
-      - name: Run Docker Test
-        run: make dockertest
-
-      #      - name: Submit Coveralls
-      #        env:
-      #          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      #        run: goveralls -coverprofile=cover.profile -service=github
-
-      - name: Login to Docker Hub
-        uses: docker/login-action@v3
-        with:
-          username: ${{ env.USERNAME }}
-          password: ${{ secrets.DOCKER_PASS }}
-
-      - name: Automatic Tagging of Releases
-        id: increment-git-tag
-        run: |
-          chmod +x scripts/git_update_tag.sh
-          bash scripts/git_update_tag.sh -v patch
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
-      - name: Push user to Docker Hub
-        id: build-push-user-db-image
-        env:
-          IMAGE_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
-        run: |
-          cd docker/user
-          docker build -t $GROUP/$REPO_USER:$IMAGE_TAG .
-          docker push $GROUP/$REPO_USER:$IMAGE_TAG
-
-      - name: Push user to Docker Hub
-        id: build-push-user-image
-        env:
-          IMAGE_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
-        run: |
-          cd docker/user-db
-          docker build -t $GROUP/$REPO_USER:$IMAGE_TAG .
-          docker push $GROUP/$REPO_USER_DB:$IMAGE_TAG
+          ls
+#          make deps
+#          wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
+#          sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb
+#
+#      - name: Install/Downgrade MongoDB to version 3.6
+#        run: |
+#          wget -qO - https://pgp.mongodb.com/server-3.6.asc | sudo tee /etc/apt/trusted.gpg.d/mongodb-org-3.6.gpg
+#          echo "deb [trusted=yes arch=amd64] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/3.6 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.6.list
+#          sudo apt-get update
+#          sudo apt-get install -y --allow-downgrades mongodb-org=3.6.20 mongodb-org-server=3.6.20 mongodb-org-shell=3.6.20 mongodb-org-mongos=3.6.20 mongodb-org-tools=3.6.20 || echo "Error is misleading, it was successfully installed"
+#
+#      #      - name: Install/Downgrade MongoDB to version 3.6
+#      #        run: |
+#      #          wget -qO - https://www.mongodb.org/static/pgp/server-3.6.asc | sudo apt-key add -
+#      #          echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/3.6 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.6.list
+#      #          sudo apt-get update
+#      #          sudo apt-get install -y --allow-downgrades mongodb-org=3.6.20 mongodb-org-server=3.6.20 mongodb-org-shell=3.6.20 mongodb-org-mongos=3.6.20 mongodb-org-tools=3.6.20 || echo "Error is misleading, it was successfully installed"
+#
+#      - name: Unit Tests
+#        run: glide novendor| xargs go test -v
+#
+#      #      - name: Create cover profile
+#      #        run: make coverprofile
+#
+#      - name: Run Docker Test
+#        run: make dockertest
+#
+#      #      - name: Submit Coveralls
+#      #        env:
+#      #          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#      #        run: goveralls -coverprofile=cover.profile -service=github
+#
+#      - name: Login to Docker Hub
+#        uses: docker/login-action@v3
+#        with:
+#          username: ${{ env.USERNAME }}
+#          password: ${{ secrets.DOCKER_PASS }}
+#
+#      - name: Automatic Tagging of Releases
+#        id: increment-git-tag
+#        run: |
+#          chmod +x scripts/git_update_tag.sh
+#          bash scripts/git_update_tag.sh -v patch
+#        env:
+#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#
+#      - name: Push user to Docker Hub
+#        id: build-push-user-db-image
+#        env:
+#          IMAGE_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
+#        run: |
+#          cd docker/user
+#          docker build -t $GROUP/$REPO_USER:$IMAGE_TAG .
+#          docker push $GROUP/$REPO_USER:$IMAGE_TAG
+#
+#      - name: Push user to Docker Hub
+#        id: build-push-user-image
+#        env:
+#          IMAGE_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
+#        run: |
+#          cd docker/user-db
+#          docker build -t $GROUP/$REPO_USER:$IMAGE_TAG .
+#          docker push $GROUP/$REPO_USER_DB:$IMAGE_TAG
 
 #      # Push to dockerhub
 #      - name: Push user to Docker Hub
